### PR TITLE
GH-1: Upgrade to SI-4.3.6 and DSL-1.2.1

### LINKED ISSUE #1: Reconsider PoorMansMailServer in favor of TestMailServer from SI-test since 4.3.6
See  https://jira.spring.io/browse/INT-4168 for more info.

### PR DESCRIPTION
**Pull request by artembilan**
Fixes spring-cloud-stream-app-starters/mail#1 GH-1 (https://github.com/spring-cloud-stream-app-starters/mail/issues/1)

Since SI-4.3.6 the `TestMailServer` is located in the `SI-test` module, therefore no need in the local `PoorMansMailServer` variant.
And from here all the `mail-app-starters-test-support` does not make sense.

* Rework `MailSourceConfigurationTests` to use `TestMailServer` from `SI-test`
* Fix tests to the new logic in the `TestMailServer`
* Also fix some inconsistent names
* Upgrade to SI-Java-DSL-1.2.1 to support `userFlag`
* Add `userFlag` option to the `mail` source
* Document a new `userFlag` property

### CODE REVIEW

**Comment by garyrussell** [comment]
Shouldn't we remove https://github.com/spring-cloud-stream-app-starters/mail/tree/master/mail-app-starters-test-support as well as removing it as a module from the pom?

**Comment by artembilan** [comment]
I think it is done already.
At least my local copy for this branch doesn't have that dir any more.
Just try to pull it locally and re-import.

**Comment by garyrussell** [comment]
Oh, I see, yes; another GitHub UI change.

**Comment by garyrussell** [comment]
The dependencies are all messed up; notice we have 4.3.6 `-core` but 4.2.5 `-mail`, `-xml`, `-jmx`:

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ spring-cloud-starter-stream-source-mail ---
[INFO] org.springframework.cloud.stream.app:spring-cloud-starter-stream-source-mail:jar:1.1.2.BUILD-SNAPSHOT
[INFO] +- org.springframework.integration:spring-integration-mail:jar:4.2.5.RELEASE:compile
[INFO] |  +- org.springframework.integration:spring-integration-core:jar:4.3.6.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-tx:jar:4.2.6.RELEASE:compile
[INFO] |  \- org.springframework:spring-context-support:jar:4.2.6.RELEASE:compile
[INFO] |     \- org.springframework:spring-beans:jar:4.2.6.RELEASE:compile
[INFO] +- org.springframework.integration:spring-integration-java-dsl:jar:1.2.1.RELEASE:compile
[INFO] |  \- org.reactivestreams:reactive-streams:jar:1.0.0:compile
[INFO] +- org.springframework.cloud.stream.app:app-starters-trigger-common:jar:1.1.1.RELEASE:compile
[INFO] +- org.springframework.cloud.stream.app:app-starters-trigger-one-common:jar:1.1.1.RELEASE:compile
[INFO] |  \- org.springframework.cloud.stream.app:app-starters-time-common:jar:1.1.1.RELEASE:compile
[INFO] +- javax.mail:javax.mail-api:jar:1.5.5:compile
[INFO] +- com.sun.mail:javax.mail:jar:1.5.5:compile
[INFO] |  \- javax.activation:activation:jar:1.1:compile
[INFO] +- org.springframework.cloud.stream.app:app-starters-test-support:jar:1.1.1.RELEASE:test
[INFO] +- org.springframework.cloud:spring-cloud-stream:jar:1.1.0.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-actuator:jar:1.3.5.RELEASE:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-actuator:jar:1.3.5.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-web:jar:1.3.5.RELEASE:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:1.3.5.RELEASE:compile
[INFO] |  |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.0.33:compile
[INFO] |  |  |  +- org.apache.tomcat.embed:tomcat-embed-logging-juli:jar:8.0.33:compile
[INFO] |  |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.0.33:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.6:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.6:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.6.6:compile
[INFO] |  |  +- org.springframework:spring-web:jar:4.2.6.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-webmvc:jar:4.2.6.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-validation:jar:1.3.5.RELEASE:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.0.33:compile
[INFO] |  |  \- org.hibernate:hibernate-validator:jar:5.2.4.Final:compile
[INFO] |  |     +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |     +- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO] |  |     \- com.fasterxml:classmate:jar:1.1.0:compile
[INFO] |  +- org.springframework:spring-messaging:jar:4.2.6.RELEASE:compile
[INFO] |  +- org.springframework.integration:spring-integration-jmx:jar:4.2.5.RELEASE:compile
[INFO] |  +- org.springframework:spring-tuple:jar:1.0.0.RELEASE:compile
[INFO] |  |  \- com.esotericsoftware:kryo-shaded:jar:3.0.3:compile
[INFO] |  |     \- com.esotericsoftware:minlog:jar:1.3.0:compile
[INFO] |  +- org.springframework.integration:spring-integration-tuple:jar:1.0.0.RELEASE:compile
[INFO] |  \- org.springframework.retry:spring-retry:jar:1.1.2.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-configuration-processor:jar:1.3.5.RELEASE:compile
[INFO] |  +- org.json:json:jar:20140107:compile
[INFO] |  \- org.springframework:spring-core:jar:4.2.6.RELEASE:compile
[INFO] +- com.jayway.jsonpath:json-path:jar:2.0.0:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.21:compile
[INFO] |  \- net.minidev:json-smart:jar:2.1.1:compile
[INFO] |     \- net.minidev:asm:jar:1.0.2:compile
[INFO] |        \- asm:asm:jar:3.3.1:compile
[INFO] +- org.springframework.integration:spring-integration-xml:jar:4.2.5.RELEASE:compile
[INFO] |  +- org.springframework.ws:spring-xml:jar:2.2.2.RELEASE:compile
[INFO] |  \- org.springframework:spring-oxm:jar:4.2.6.RELEASE:compile
[INFO] +- org.springframework.cloud:spring-cloud-stream-test-support:jar:1.1.0.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-test:jar:1.3.5.RELEASE:compile
[INFO] |  |  +- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |  |  \- org.hamcrest:hamcrest-library:jar:1.3:compile
[INFO] |  \- org.springframework.boot:spring-boot-autoconfigure:jar:1.3.5.RELEASE:compile
[INFO] |     \- org.springframework.boot:spring-boot:jar:1.3.5.RELEASE:compile
[INFO] +- org.springframework.cloud:spring-cloud-stream-test-support-internal:jar:1.1.0.RELEASE:test
[INFO] |  \- junit:junit:jar:4.12:compile
[INFO] +- org.springframework.integration:spring-integration-test:jar:4.3.6.RELEASE:test
[INFO] |  +- org.hamcrest:hamcrest-all:jar:1.3:test
[INFO] |  +- org.mockito:mockito-core:jar:1.10.19:compile
[INFO] |  |  \- org.objenesis:objenesis:jar:2.1:compile
[INFO] |  +- org.springframework:spring-context:jar:4.2.6.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-expression:jar:4.2.6.RELEASE:compile
[INFO] |  \- org.springframework:spring-test:jar:4.2.6.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot-starter-logging:jar:1.3.5.RELEASE:compile
[INFO] |  +- ch.qos.logback:logback-classic:jar:1.1.7:compile
[INFO] |  |  \- ch.qos.logback:logback-core:jar:1.1.7:compile
[INFO] |  +- org.slf4j:jcl-over-slf4j:jar:1.7.21:compile
[INFO] |  +- org.slf4j:jul-to-slf4j:jar:1.7.21:compile
[INFO] |  \- org.slf4j:log4j-over-slf4j:jar:1.7.21:compile
[INFO] \- org.springframework.boot:spring-boot-starter-security:jar:1.3.5.RELEASE:compile
[INFO]    +- org.springframework.boot:spring-boot-starter:jar:1.3.5.RELEASE:compile
[INFO]    |  \- org.yaml:snakeyaml:jar:1.16:runtime
[INFO]    +- org.springframework:spring-aop:jar:4.2.6.RELEASE:compile
[INFO]    |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO]    +- org.springframework.security:spring-security-config:jar:4.0.4.RELEASE:compile
[INFO]    |  \- org.springframework.security:spring-security-core:jar:4.0.4.RELEASE:compile
[INFO]    \- org.springframework.security:spring-security-web:jar:4.0.4.RELEASE:compile
[INFO]                                                                         
```

**Comment by artembilan** [comment]
Eh... And pay attention how it is with `spring-boot-1.3.5`...

**Comment by artembilan** [comment]
M-m-m. 
A couple questions:
- how to generate the target SCSt application for this project?
- how to override dependencies versions to desired? 

/CC @sobychacko 

Thanks

**Comment by garyrussell** [comment]
So what's the goal of this PR, given that the underlying code uses SI 4.2? (and a very old version of 4.2 at that).

**Comment by artembilan** [comment]
My goal to reach the purpose of this GH org: 
provide custom versions for dependencies to particular project and get a gain from the Microservices Universe, when my customized application isn't affected with galaxies close by.

**Comment by sobychacko** [comment]
@artembilan @garyrussell Added the SI bom for 4.3.6.RELEASE in `mail-app-dependencies` and that will override all transitive SI dependencies. Please see my latest commit with the merge.

**Comment by sobychacko** [comment]
@artembilan You can generate the target SCSt application as you would do normally by using the `generateApps` maven profile.
For overriding SI dependencies, please refer to my last commit with the merge.

**Comment by artembilan** [comment]
@sobychacko , @garyrussell ,

I've just tested the latest changes in the `app-starters-core` and `spring-cloud-stream-app-maven-plugin` with this `mail` project and I'm happy to say that I see this in the final `mail-source-rabbit` pom:
```
 <properties>
    <skipTests>true</skipTests>
    <java.version>1.7</java.version>
    <spring-integration-java-dsl.version>1.2.1.RELEASE</spring-integration-java-dsl.version>
    <spring-integration.version>4.3.6.RELEASE</spring-integration.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud.stream.app</groupId>
        <artifactId>mail-app-dependencies</artifactId>
        <version>1.1.2.BUILD-SNAPSHOT</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.springframework.cloud.stream.app</groupId>
        <artifactId>app-starters-core-dependencies</artifactId>
        <version>1.1.2.BUILD-SNAPSHOT</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```
And the target uber jar has proper dependency versions for SI as well as for SI Java DSL.
So, I think we have reached a goal of this task and can close this PR. At last 😄 

For the future to be sure that we "force" a desired version for an existing Boot dependency we should the same  POM property name as it is in the `spring-boot-dependencies`. For example if we would like to use Spring AMQP 1.7.0`  instead of current `1.6.6` in Boot 1.4, we should specify in our POM:
```
<spring-amqp.version> 1.7.0.RC1</spring-amqp.version>
```

More version properties are here in Boot: https://github.com/spring-projects/spring-boot/blob/1.4.x/spring-boot-dependencies/pom.xml

**Comment by garyrussell** [comment]
LGTM now; but perhaps we should bump SF to 4.3.5 to match the default for SI 4.3.6

**Comment by artembilan** [comment]
Yeah... That is already a part of Spring Boot `1.4.3`: https://github.com/spring-projects/spring-boot/blob/v1.4.3.RELEASE/spring-boot-dependencies/pom.xml.
But since this project depends on Spring Cloud Build it pulls Boot 1.4.1.

I think since we still compatible with that SF version there no reason to upgrade all the transitive dependencies.
The main reason of this exercise to be sure that we can fix one particular application without affect for all others.
IMO the goal is reached, no reason to complicate it farther.

**Comment by sobychacko** [comment]
Closing the PR.

**Comment by garyrussell** [comment]
I would be more comfortable if everything was aligned - why can't we force the boot version to 1.4.3?

**Comment by sobychacko** [comment]
The Avogadro release train for app starters depend on SCSt Brooklyn and it transitively depend on Boot 1.4.1. Thus, when generating the apps, we default all the apps to use Boot 1.4.1 as well. That being said, we can force Boot 1.4.3 at the compile level for the mail starter and in the generated apps at runtime. For the next release train (Bacon), these dependencies are going to be upgraded anyways at the core level. 

So what do you think? Shall we force 1.4.3 just for the mail app now?

**Comment by artembilan** [comment]
M-m-m. I think the question is more about how much this our spaceship has control over its equipment on the way not involving a support Earth?
Can't it just upgrade a Spring Boot to 1.5, for example, and make a better quantum leap in this Microservice Universe?

We don't such an upgrade here in `mail` app, but just theoretical question for potential wishes in other places.

**Comment by garyrussell** [comment]
In this case, I am not too worried (in fact SF 4.3.4 and 4.3.5 have some performance impacts on SI) so sticking at 4.3.3 is ok.

I am just raising the issue as to whether we should generally cherry-pick, or stick with IO (boot) compatible versions only.

**Comment by sobychacko** [comment]
we can cherry-pick dependency overrides for a specific app starter if that is a hard requirement. However, for core elements like SF, boot etc. I think it is best to rely on the same versions that the underlying SCSt uses as these are ultimately SCSt based apps. @mbogoevici what do you think?

**Comment by mbogoevici** [comment]
@sobychacko Yes - unless we have some really hard requirement, it is much easier if we don't override versions

**Comment by sobychacko** [comment]
All the issues on this PR have been addressed and resolved. Closing.

**Pull request closed without merging**
